### ISSUE TITLE
settings not inherited

### ISSUE THREAD

**Issue by activestylus** [cyx/cuba-contrib#3]
If I define `Cuba.settings[:layout] = "default"`

Then I subclass Cuba

```
class Sites > Cuba

  ...

end
```

My page loads an error now saying that my layout is not defined. It does not work until I paste it in there 

```
class Sites > Cuba

  settings[:layout] = "default"
  ...

end
```

Now it works fine, but it does get cumbersome and repetitive to do this for every single routes class.

Any idea why it's not inheriting the setting?

**Comment by activestylus** [comment]
Turns out this was just a weird bug with Rubinius - works perfectly in 1.9.3. I'm closing this and hitting up the rbx channel

**Comment by cyx** [comment]
Hi,

Thanks again for checking with 1.9.3 yourself. Let me know if you find anything else interesting! ^_^
