### ISSUE TITLE
Override layout's parent directory

### ISSUE THREAD

**Issue by activestylus** [cyx/cuba-contrib#4]
Right now specifying `settings[:layout]` just concatenates onto `settings[:view]` 

As someone who uses multiple view paths and has several apps referencing one layout, I'd like to be able to specify the layout path the same way that I specify views path

Will probably just patch this myself, but curious how you would handle making the change backwards compatible.

**Comment by activestylus** [comment]
I'm going to close this one too, cause I realize its an edge case and I dont want to mess with such a sweet and simple code base. I have temporarily bypassed the problem by symlinking my shared folders.

**Comment by activestylus** [comment]
FWIW, I actually found a better solution. Just monkey patched some Mote methods:

```
def view(template, locals = {}, layout = settings[:layout])
  raise NoLayout.new(self) unless layout
  render_with_layout(layout, locals.merge(mote_vars(partial(template, locals))))
end

def render_with_layout(layout, locals={})
  path = File.expand_path("app/shared/layouts/#{layout}.mote")
  mote(path, locals)
end
```

**Comment by cyx** [comment]
Hi,

Thanks for this and for your creative solution!

Actually I've done this in the past by passing in the full path of the layout. I apologize for not documenting that
feature properly.

I added a test for that just to make sure that it works as intended. See here:

https://github.com/cyx/cuba-contrib/commit/0ce272dd7dc70426db4a669cdd5cef79ad301f06

Let me know if this was what you meant.

**Comment by activestylus** [comment]
Yes that is what I meant. Although your example didn't work for me, all it does is append the string to the view path

so if I say `settings[:layout]= './views'` it will throw an error

```
No such file or directory - /app/sub-app/./views/index.mote
```

I tried a bunch of different ways but my hack was the only one that worked. The reason for this is that you are using nested partial calls and the partial helper always looks to the `mote_path()`, so anything you specify to `settings[:layout]` just gets tacked on to the end of the `settings[:view]` string. I am surprised that your tests are passing!

Looking at your commit I do have two questions

(1) I see you are hitting the current directory with "./" - as I understand it this is discouraged for security reasons
(2) Looking at your tests I could not help but wonder what the heck this is

```
_, _, body = Cuba.call({ "PATH_INFO" => "/frag", "SCRIPT_NAME" => "" })
```

What is that business with setting those underscore variables? You use the same symbol twice and there is no reference to them in the test later on. I have seen this pattern before but never grokked it.

**Comment by cyx** [comment]
Hi,

> I tried a bunch of different ways but my hack was the only one that worked. The reason for this is that you are using nested partial calls and the partial helper always looks to the mote_path(), so anything you specify to `settings[:layout]` just gets tacked on to the end of the settings[:view] string. I am surprised that your tests are passing!

Hmm maybe you can gist your exact code (the ones related) so I can analyze what's happening in your case. Not necessary,
only if you want to.

> Looking at your commit I do have two questions
> 
> (1) I see you are hitting the current directory with "./" - as I understand it this is discouraged for security reasons

Yeah it's just for doing stuff quicker. For the specific case of my test, there's no real security concern, it's mostly
related to injected paths / user data fetched from non-trusted sources iirc.

The better approach is to do File.join('…', Dir.pwd) now that you mention it. :-)

> (2) Looking at your tests I could not help but wonder what the heck this is
> 
> ```
> _, _, body = Cuba.call({ "PATH_INFO" => "/frag", "SCRIPT_NAME" => "" })
> ```

This consttruct basically means, I don't care about the first two return values. I'm not entirely sure where this convention
first came up, but I first saw Chris Neukirchen doing this.

Haskell does this with pattern matching to mean "anything for the following" too so maybe that had an influence as well.

Thanks,
cyx

**Comment by activestylus** [comment]
Thanks for the info - I've forked this gem and will try to add some breaking tests to it.
