### ISSUE TITLE
Cuba::Rendering not defined

### ISSUE THREAD

**Issue by activestylus** [cyx/cuba-contrib#7]
Apparently this lib only supports Mote now. The README should be updated

I get undefined module when I rum `Cuba.plugin Cuba::Rendering`

Also the `Cuba.set` method no longer exists

**Comment by cyx** [comment]
Hi @activestylus,

Trying to find where this is mentioned, but couldn't.

**Comment by activestylus** [comment]
https://github.com/cyx/cuba-contrib#classic-templating-needs

**Comment by cyx** [comment]
Thanks! I was confused for a moment and assumed that you were referring to cuba README, not cuba-contrib.

^_^
